/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Daniel Sánchez' at '5/01/16 17:52' with Gradle 2.9
 *
 * @author Daniel Sánchez, @date 5/01/16 17:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
	
	public static void main( String[] args )
    {
        System.out.println( "Hola Mundo!" );
    }
}
