import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Daniel Sánchez' at '5/01/16 17:52' with Gradle 2.9
 *
 * @author Daniel Sánchez, @date 5/01/16 17:52
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", !classUnderTest.someLibraryMethod());
    }
}
